# root folder where the source and output folders belong
base_data_folder: "."
debug: false
labels: [bird, cat, false-positive, hedgehog, insect, leporidae, mustelid, possum,
  rodent, wallaby]
previews_colour_map: custom_colormap.dat
verbose: false
source_folder: cptv
# tracks_folder is where the track data files will be created. It is
# specified relative to base_data_folder.
tracks_folder: tracks
use_opt_flow: false
worker_threads: 1
build:
  banned_clips: null
 # number of frames each segment should be
  segment_length: 25

  # number of seconds each segment should be spaced apart
  segment_spacing: 1

  segment_min_avg_mass: 10
  # read all files in here of type .list and parsre each line as clipid to be used
  #  in test set
  test_clips_folder: testset
classify:
  #cache buffer frame to disk reducing memory usage
  cache_to_disk: false

  # folder is where classifier output and mp4s will be created.  It is specified relative to the base_data_folder
  classify_folder: classify
  # Writes metadata to standard out instead of a file with extension .txt
  meta_to_stdout: false
  models:
  - id: 2
    ignored_tags: []
    model_file: <path to model>/saved_model.pb
    model_weights: null
    name: Inc3
    tag_scores: {default: 0}
    thumbnail_model: false
    wallaby: false
  # Create a MP4 preview after classification of recording.  Options are "none", "raw", "classified", "tracking"
  # See extract:preview for details on each option.
  preview: tracking
load:
  cache_to_disk: false
  # odnt think this is used or safe (TO BE TESTED OR REMOVED GP)
  enable_compression: false
  high_quality_optical_flow: false
  include_filtered_channel: true
  preview: null
  # precidence of tags (lower first)
  tag_precedence: {bad track: 2, bird: 0, cat: 0, default: 3, dog: 0, false-positive: 0,
    hedgehog: 0, human: 0, insect: 0, kiwi: 0, leporidae: 0, mustelid: 0, other: 1,
    part: 2, pest: 0, possum: 0, rodent: 0, unidentified: 1, wallaby: 0}
  # dont add any tracks with these tags
  excluded_tags: [untagged, dog, unidentified, hard, multi, moving, bird-kiwi, for_grant,
    missclassified, other, part, poor tracking]
tracking:
  areas_of_interest: {cropped_regions_strategy: cautious, min_mass: 9.0, pixel_variance: 2.0}
  dilation_pixels: 2
  edge_pixels: 1
  enable_track_output: true
  filters: {min_duration_secs: 1.0, moving_vel_thresh: 4, track_min_delta: 1.0, track_min_mass: 2.0,
    track_min_offset: 4.0, track_overlap_ratio: 0.5}
  flow_threshold: 40
  frame_padding: 4
  high_quality_optical_flow: false
  max_blank_percent: 30
  max_mass_std_percent: 0.55
  max_jitter: 20
  max_tracks: 10
  min_moving_frames: 2
  min_tag_confidence: 0.6
  motion:
    camera_thresholds:
      default-model: {background_thresh: 20, camera_model: default-model, default: false,
        max_temp_thresh: null, min_temp_thresh: null, temp_thresh: 2900, track_max_delta: 150,
        track_min_delta: 1.0}
      lepton3: {background_thresh: 20, camera_model: lepton3, default: true, max_temp_thresh: null,
        min_temp_thresh: null, temp_thresh: 2900, track_max_delta: 150, track_min_delta: 1.0}
      lepton3.5: {background_thresh: 50, camera_model: lepton3.5, default: false,
        max_temp_thresh: null, min_temp_thresh: null, temp_thresh: 28000, track_max_delta: 1500,
        track_min_delta: 50}
    dynamic_thresh: true
  remove_track_after_frames: 18
  stats: {max_threshold: 50, min_threshold: 30, threshold_percentile: 99.9}
  threshold_percentile: 99.9
  track_smoothing: false
train:
  epochs: 3
  hyper_params:
    batch_size: 8
    buffer_size: 128
    dense_sizes: []
    dropout: 0.3
    frame_size: 32
    keep_edge: true
    label_smoothing: 0.1
    learning_rate: 0.001
    learning_rate_decay: 1.0
    lstm: false
    lstm_units: 25
    maximum_train_preload: 600
    model_name: inceptionv3
    segment_type: ALL_RANDOM
    shuffle: true
    square_width: 5
    red_type: thermal_tiled
    blue_type: filtered_tiled
    green_type: filtered_tiled
    use_segments: true
  label_probabilities: {bird: 20, cat: 5, false-positive: 1, hedgehog: 20, human: 1,
    insect: 1, leporidae: 5, mustelid: 5, possum: 20, rodent: 20, vehicle: 1, wallaby: 5}

  train_dir: train
