######################################
# Author Matthew Aitchison
# Date: 20/Dec/2017
######################################
#
# Script to evaluate the performance of the classifier.
#
# Runs through a folder containing the output stats file generated by the classifer and checks how often it was correct.
# For this to work the input CPTV files must have had a ".txt" file along side them that contains the pre-tagged tagging
# information.
#
# CPTV files are clustered into visits under the following rules:
#
#     If two clips are more than 3 minutes apart start a new visit
#     If two clips differ on tag start a new visits
#
# CPTV files with two or more different tags are excluded from analysis.
#
from evaluate.main import main


main()
